### ISSUE TITLE
ORCID ID icons

### ISSUE THREAD

**Issue by TomWagg** [rodluger/showyourwork#42]
What's the best way to include the ORCID ID icons so that they appear next to author names?

Like this: 
<img width="642" alt="image" src="https://user-images.githubusercontent.com/21990332/139930707-6a27354f-8c83-45a6-b329-22743fccf0fd.png">
Instead of this:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/21990332/139930762-4cfab420-d111-464a-b062-ac6db290d510.png">

It seems like aastex requires us to put it in the same directory as `ms.tex` but showyourwork doesn't like that (both in terms of the .gitignore file and because it deletes all pngs from here every time you make). I tried adding it to `static/` instead but then they don't show up.

**Comment by rodluger** [comment]
Good question. It looks like the ID icon shows up when I build locally, but not when showyourwork builds it on GitHub Actions. Can you confirm this behavior for your paper? I'm not sure why this is happening, but I'll look into it.

**Comment by TomWagg** [comment]
Yup I found exactly the same thing, for some reason it works locally ¯\_(ツ)_/¯

**Comment by rodluger** [comment]
The issue was the capitalization of the file ``orcid-ID.png``, which is referred to in the ``AASTeX`` class file as ``Orcid-ID.png``. Macs don't care about this, but Linux machines do, which explains why things worked locally but failed on CI. I ended up changing the name of the PNG file in the class file, since re-naming the file itself is bound to cause issues with ``git`` (which is itself case-insensitive). Do a 

```bash
make update
```

when you get a chance and this should be working now!

**Comment by TomWagg** [comment]
Ahhh gotcha, that makes sense. I can confirm that your fix worked! 😄
