### ISSUE TITLE
Customise github icon colour?

### ISSUE THREAD

**Issue by TomWagg** [rodluger/showyourwork#43]
Is it possible to customise the colour of the GitHub icons? Like maybe define a colour at the top of `ms.tex` and then showyourwork uses that for all of the GitHub icons?

I'm using other links to documentation in lots of equations (e.g. Equation 2 in section 4.1 [of this pdf](https://raw.githubusercontent.com/TeamLEGWORK/LEGWORK-paper/main-pdf/ms.pdf)) and would love if I could make them match my colour scheme! 😄

**Comment by rodluger** [comment]
It's undocumented, but yes.

``showyourwork`` colors correspond to "error codes". Blue means all figures are up to date and the scripts are properly version controlled; yellow means you have untracked changes and the figure is stale; orange and red mean either the script isn't tracked by git or it doesn't exist.

Those are all defined here: https://github.com/rodluger/showyourwork/blob/7b3d8148f465e3b27892fb44d71b8b101363b51c/workflow/resources/templates/showyourwork.sty#L90

You can just override the ``sywScriptUpToDate`` color to be whatever you like in your ``ms.tex``. Add this close to the top of your document, before the abstract:

```TeX
\definecolor{seagreen}{rgb}{0.18,0.55,0.34}
\colorlet{sywScriptUpToDate}{seagreen}
```

Note that since this is undocumented, these names might change; if you update showyourwork, keep an eye on the changelogs to see if you need to edit this in the future.

**Comment by TomWagg** [comment]
Perfect, thanks so much @rodluger!!

**Comment by rodluger** [comment]
For sure. Keep these issues coming -- they're super helpful for me!
