### ISSUE TITLE
Github action not pulling Zenodo data

### ISSUE THREAD

**Issue by arm61** [rodluger/showyourwork#66]
Hey, I am trying to get my workflow to pull from Zenodo in a similar fashion to the many many dependencies example (https://showyourwork.readthedocs.io/en/v0.1.35/custom/#many-many-dependencies). But I get a 
```
snakemake.exceptions.MissingInputException: Missing input files for rule figure:
2112
  src/data/random_walks/kinisi/true/packed_1_128_128_s1024.npz
2113
  src/data/random_walks/kinisi/correlated/packed_1_128_128_s1024.npz
```
error. Where those files are ones that should be obtained from Zenodo. I can't see any indication that it is pulling or untarring the files from Zenodo. Am I missing something? (my `yml`/`yml.jinja` is basically the same as the example).

**Comment by rodluger** [comment]
Do you have a section in either your `showyourwork.yml.jinja` or your `Snakefile` instructing `showyourwork` how to obtain those files? This is not explicitly shown in the example you linked to, but if you look at the full `Snakefile` for that example, you'll see that I define a rule to generate them: https://github.com/rodluger/showyourwork-example/blob/db6feb49746ee749746b37b0e3e14fb15b9bc984/Snakefile#L24-L34

Since you're downloading from Zenodo, you'll likely want a `zenodo:` key in the `showyourwork.yml.jinja` for the tarball containing those files. Do you have something like that already?

**Comment by arm61** [comment]
Ahh I think I see where my issue is. I need to change (again) how I am packaging my data.

**Comment by arm61** [comment]
Okay, I have fixed this one but created a new error for myself. I will close this and open something new!
