### ISSUE TITLE
Documentation header links under "Contents" (right sidebar) not working

### ISSUE THREAD

**Issue by adrn** [rodluger/showyourwork#81]
For me, in Brave or Chrome, the right sidebar heading links aren't working. For example:
https://showyourwork.readthedocs.io/en/stable/custom/#custom-figure-rules

Is not going to the heading "Custom figure rules"

**Comment by rodluger** [comment]
I run into this occasionally as well. It seems to happen randomly -- for some builds the links are fine, for others they don't work. See, for instance, the build for `latest`: https://showyourwork.readthedocs.io/en/latest/custom/#custom-figure-rules, which is currently working. (It's the same commit -- just generated by different builds on readthedocs).

I haven't been able to figure out where the issue is. Even when the links to work, it's clear that the HTML anchors are working. Do you have any ideas?

**Comment by dfm** [comment]
My browser emits this warning on the page that doesn't work:

> Scroll anchoring was disabled in a scroll container because of too many consecutive adjustments (10) with too little total distance (-1.70499992370605 px average, -17.05 px total).

This might have something to do with it?

**Comment by rodluger** [comment]
Good to know! Sounds like an issue with the template, perhaps? I think you use the same Executable Book Project template for exoplanet, @dfm -- have you never run into this?

**Comment by dfm** [comment]
Not that I know of! But, yeah I might guess that it has something to do with all the differently scrolled sections? No good ideas!

**Comment by rodluger** [comment]
I'm re-building the docs for the next version of `showyourwork`, so I'll make sure this is working for that.
